name: uvtls CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt-get install libuv1-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ./test-uvtls

